name: Deploy Django Backend

on:
  push:
    branches: [ "backend" ]
  pull_request:
    branches: [ "backend" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_PROJECT_DIR: ${{ secrets.EC2_PROJECT_DIR }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.7'

      - name: Install dependencies
        run: pip install -r backend/olympic_project/requirements.txt

      - name: Deploy to EC2
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
            mkdir -p $EC2_PROJECT_DIR
            cd $EC2_PROJECT_DIR
            git pull origin main
            source venv/bin/activate
            pip install -r backend/olympic_project/requirements.txt
            python manage.py migrate
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF
        shell: bash
